dream:
  weixin:
    dev-mode: true
    url-patterns: /weixin/**
    app-id-key: appId
    wx-configs:
#      可自定义 WxConfigLoader 用于从数据库等地方加载配置
#      - appId: wxc03edcd008ad1e70
#        appSecret: 11ed9e2b8e3e3c131e7be320a42b2b5a
#        token: 123456
      - appId: wx9803d1188fa5fbda
        appSecret: db859c968763c582794e7c3d003c3d87
        token: 123456
        encodingAesKey: xxx
        messageEncrypt: true
    wxa-configs:
      - app-id: wx4f53594f9a6b3dcb
        app-secret: eec6482ba3804df05bd10895bace0579
      - app-id: wx1111111111111111
        app-secret: eec6482ba3804df05bd10895bace0579
    json-type: jackson
